jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: cat -v file.c file.txt
    displayName: 'Linux test'
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - bash: cat -v file.c file.txt
    displayName: 'Windows test'
