jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      mingw32:
        wordsize: 32
      mingw64:
        wordsize: 64
  steps:
  - script: |
    choco install msys2
    C:\tools\msys64\usr\bin\env.exe MSYSTEM=MINGW64 /bin/bash -l %CD%/build %1
