#!/bin/bash
set -ex
curl -L https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.2.1/qpdf-8.2.1.tar.gz -o qpdf-8.2.1.tar.gz
tar xzf qpdf-8.2.1.tar.gz
cd qpdf-8.2.1
./configure --enable-werror --enable-show-failed-test-output
make -j$(nproc)
make check
