#!/bin/bash
set -x

#ls -lR "$VS140COMNTOOLS"
#cat "$VS140COMNTOOLS/vsvars32.bat"
#ls -lR "$VS140COMNTOOLS/../.."



ls -l $"VS140COMNTOOLS/../../VC/bin"
ls -l $"VS140COMNTOOLS/../../VC/bin/amd64"
ls -l $"VS140COMNTOOLS/../../VC/bin/"*.bat
ls -l $"VS140COMNTOOLS/../../VC/bin/amd64/"*.bat

#find "/c" -name 'vcvars*.bat' -print
exit 0


cl
g++ --version
curl -L https://downloads.sourceforge.net/project/qpdf/external-libs/2017-08-21/qpdf-external-libs-bin.zip -o qpdf-external-libs-bin.zip
curl -L https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.2.1/qpdf-8.2.1.tar.gz -o qpdf-8.2.1.tar.gz
tar xzf qpdf-8.2.1.tar.gz
cd qpdf-8.2.1
unzip ../qpdf-external-libs-bin.zip
cwd=`pwd`
PATH=$cwd/libqpdf/build:$PATH
for i in mingw msvc; do
    rm -rf {install,qtest}-$i$wordsize
    # XXX show failed output instead of thing below
    ./config-$i
    make -j8
    make -k check || \
        { mkdir qtest-$i$wordsize; \
          tar cf - */build/qtest.log | (cd qtest-$i$wordsize; tar xf -) }
    make install
    make distclean
done
